server:
  port: 8000
  servlet:
    context-path: /

spring:
  application:
    name: terabox-api-sp

# TeraBox API Configuration
terabox:
  # Array of cookies - Add your cookies here
  cookies:
    - "ndus=Yz4-0L9peHuimpLYWYYjBJBKq3tu8vhPcndgD3AE"
    - "ndus=YqFP0L9peHuiyFFw0CLlNFiaMNq1mshm4zAVYnTd"
    - "ndus=Y-q90L9peHuiIz6QKAF8-C5UGRi4ksJVvkVm-6fB"
    - "ndus=YzAY0L9peHuiooD2HIQfRKqdMaQ6ZiK1lw1-RGs4"
    - "ndus=YuBr0L9peHui5KMxuQ16Zg9V8_G67OXqf3p5hMna"
    - "ndus=YdAZ0L9peHuipVO_a0gjom0pwVPAx27DYL-hryog"
    - "ndus=Yfpi0B9peHuiKia5r7FlRJPoaaF9N9Syuaw-ikqa"
    - "ndus=Yypi0B9peHuiKjsIEa4lZTrqciAh_i_pb-I_ul_2"
    - "ndus=YyYm0B9peHuiBrHdNsFrn6AtTd4We26B6tNtVWCv"
    - "ndus=YynP0B9peHui3Fxq4OhG0ZmaQnQzgOttREvVW0K9"
    - "ndus=YbYw0B9peHuiTWLKP-f338RHwZKJ8-xfRTlChYIr"
    - "ndus=YQK30B9peHuiWfikXCUNEWYOQccREJK43hqjkDL_"
    - "ndus=YTnX0B9peHuid1xZK0NS7pWCE6bcvwEop3wdcBGA"
    - "ndus=YeCX0B9peHuijmTMgDai-zit3fz8zrr7Dkmwyzj9"
    - "ndus=Ydpr0B9peHuiWoqXarqMYFzkQMxd7L5IwUnEfP60"
    - "ndus=Yzik0L9peHuiHAu_JQc3PO7GqujFTB-UHP6d8u1i"
    - "ndus=Y4B70L9peHui30o2uueU6m30icNre2VTSlucHgIw"
    - "ndus=Y2FI0L9peHuiXfU64vAhizKkqF0QtlDVxigeHoVA"
    - "ndus=Yukf0L9peHuiOyRyIOC_tp1la7Jb8a9OXNckfUq7"
    - "ndus=YQhv0L9peHuiZeoeQ65GaSHp1iXNRQl3N6JQwbCc"
    - "ndus=YbcR0L9peHuif_1ELqXtAEz7_yJhVP6o1sF0ET6K"
    - "ndus=YTtN0X9peHuiHBPyHRLjN4tGF-gb6l17RGe59kh_"
    - "ndus=YvDU0X9peHuizaVCM8fZvjzZj6MsyREqexVS1xJI"
    - "ndus=YzIU0X9peHuizOdMB2MRck43YJBomhdDjp-XsdTt"
    - "ndus=Y-QS0X9peHuif14g_6siGwoGX9G-hOXj2dhUW2Fn"
    - "ndus=YvFq0X9peHui_UXI3fPKbK0cjDMTHiJqRxRcZKR3"

  
  # HTTP Client Configuration
  http:
    connect-timeout: 30000  # 30 seconds
    read-timeout: 60000     # 60 seconds
    write-timeout: 60000    # 60 seconds
  
  # Retry Configuration
  retry:
    max-attempts: 3
    backoff-delay: 2000  # 2 seconds

  # Async Configuration (for parallel processing)
  async:
    enabled: true           # Enable/disable async processing
    core-pool-size: 10      # Core thread pool size
    max-pool-size: 50       # Maximum thread pool size
    queue-capacity: 100     # Task queue capacity

  # Proxy Configuration (DC Proxy)
  proxy:
    enabled: true
    username: "spyblwudx2"
    password: "w3BhL6lhGc~mnP3dc1"
    host: "dc.decodo.com"
    start-port: 10001
    end-port: 10100

# Logging Configuration
logging:
  level:
    root: INFO
    com.terabox.api: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

